# Generated by Django 4.1.6 on 2023-02-11 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0002_remove_sectionprimary_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionprimary',
            old_name='position',
            new_name='slug',
        ),
    ]
