# Generated by Django 4.1.6 on 2023-02-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0005_sectionprimary_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionprimary',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
