# Generated by Django 4.1.6 on 2023-02-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0006_sectionprimary_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionprimary',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
