# Generated by Django 4.1.6 on 2023-02-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0007_sectionprimary_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionprimary',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
