# Generated by Django 4.1.6 on 2023-02-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0009_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='school_name',
            field=models.CharField(max_length=500),
        ),
    ]
